import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { WalletNames, connect } from '@glitch-txs/w3/dist'
import trust from 'public/trust_white.svg'
import coinbaseLogo from 'public/coinbase.svg'
import walletconnect from 'public/walletconnect.svg'
import metamask from 'public/metamask.svg'
import phantom from 'public/phantom.svg'
import Image from 'next/image'

type Wallets = {
  name:WalletNames
  image:any
}


const wallets: Wallets[] = [
  {
    name: 'MetaMask',
    image: metamask
  },
  {
    name:'Coinbase',
    image: coinbaseLogo
  },
  {
    name:'Phantom',
    image:phantom
  },
  {
    name:'Trust Wallet',
    image:trust
  },
  {
    name:'WalletConnect',
    image:walletconnect
  }
] 

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {wallets.map(v=><button key={v.name} className={[styles.wallet, false && styles.loading].join(' ')} onClick={()=>connect(v.name)}>
          <span>
            <Image width={44} src={v.image} alt='' />
          </span>
          {v.name}
        </button>)}
      </main>
    </>
  )
}
