import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Modal, openModal } from 'walletconnect-legacy-ui'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Modal/>
        <button onClick={openModal}>Open Modal</button>
      </main>
    </>
  )
}
