import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { openModal } from 'walletconnect-legacy-ui'
import { disconnectW3, getW3Address } from 'w3-evm-react'
export default function Home() {

  const address = getW3Address()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={openModal}>Open Modal</button>

        {address &&
          <>
            <div> Address: {address} </div>
            <button onClick={disconnectW3}>Disconnect</button>
          </>
        }
      </main>
    </>
  )
}
