import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import { setOpen } from '@/modal/store'

const Modal = dynamic(async()=>await import('../../src/modal'), {
  ssr: false
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Modal/>
        <button onClick={setOpen}>Open Modal</button>
      </main>
    </>
  )
}
